#!/usr/bin/env python3
"""
Give each hand-drawn diagram its own copy of the typeface it asks for.

    python3 tools/embed_diagram_fonts.py            # rewrite every d-*.svg
    python3 tools/embed_diagram_fonts.py --check    # fail if any is unembedded

**The problem.** Every `d-*.svg` names its typeface and ships no glyphs:

    <svg ... font-family="'Source Sans 3','Source Sans Pro',...,sans-serif">

The decks embed them as `<img src="../assets/figures/d-kfold.svg">`, and an SVG
inside an `<img>` is a *separate document rendered in secure static mode*. It
cannot see the page's `@font-face`, and it is not allowed to fetch anything
external — no stylesheet, no font file, not even a same-origin one. So the only
way it gets Source Sans 3 is if the machine has Source Sans 3 installed. This
one does not, and a lecture-theatre machine will not either.

Every hand-drawn diagram in this course has therefore been rendering in
Helvetica, next to matplotlib figures rendering in Source Sans 3, on the same
slide. matplotlib is unaffected because `svg.fonttype` defaults to `path`: its
output carries its own outlines — `l24-concentration.svg` embeds 365 of them,
`d-course-arc.svg` embeds none.

**Worse than a cosmetic difference**, it silently invalidated measurement.
`tools/check_diagrams.py` inlines each SVG into a page that links the course
stylesheet, so *it* renders in Source Sans 3 — it was measuring label widths in
a typeface the projector never uses. Every "this label fits" was answered about
the wrong font. `--check` here is what stops that recurring, and check_diagrams
now renders through `<img>` for the same reason.

**The fix.** Subset the vendored variable font to exactly the characters each
diagram uses, at the weights it uses, and inline it as a base64 `@font-face` in
that file. Roughly 10 KB a face rather than 25 KB, because a diagram uses forty
characters and not a hundred and twenty. This is self-containment of the same
kind matplotlib already gives us, and it survives being opened anywhere by
anyone.

Rerunning is safe: the injected block is delimited and replaced, not stacked.
"""

from __future__ import annotations

import argparse
import base64
import html
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIGURES = ROOT / "assets" / "figures"
FONTS = ROOT / "assets" / "fonts"

MARK_OPEN = "<!-- embedded-fonts: generated by tools/embed_diagram_fonts.py -->"
MARK_CLOSE = "<!-- /embedded-fonts -->"

# (face key) -> (source file, weight, style)
FACES = {
    "regular": (FONTS / "SourceSans3-VF.ttf", 400, "normal"),
    "bold":    (FONTS / "SourceSans3-VF.ttf", 700, "normal"),
    "italic":  (FONTS / "SourceSans3-Italic-VF.ttf", 400, "italic"),
}

_cache: dict[tuple[str, str], str] = {}


def subset_b64(face: str, text: str) -> str:
    """Base64 woff2 of `face`, cut down to `text`. Cached per (face, charset)."""
    key = (face, "".join(sorted(set(text))))
    if key in _cache:
        return _cache[key]

    from fontTools import subset
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer

    src, wght, _style = FACES[face]
    font = TTFont(src)
    if "fvar" in font:
        # Pin the weight rather than shipping the variation machinery: a static
        # instance of forty glyphs is a fraction of the size, and nothing in a
        # diagram animates its weight.
        font = instancer.instantiateVariableFont(font, {"wght": wght})
    opts = subset.Options(layout_features=["*"], notdef_outline=True,
                          desubroutinize=True)
    opts.flavor = "woff2"
    sub = subset.Subsetter(options=opts)
    sub.populate(text=text + " ")
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    out = base64.b64encode(buf.getvalue()).decode("ascii")
    _cache[key] = out
    return out


def characters(svg: str) -> str:
    """Every character the file actually draws."""
    chars: set[str] = set()
    for m in re.finditer(r"<text[^>]*>(.*?)</text>", svg, re.S):
        chars |= set(html.unescape(re.sub(r"<[^>]+>", "", m.group(1))))
    return "".join(sorted(c for c in chars if c.strip()))


def faces_needed(svg: str) -> list[str]:
    """Which cuts this file asks for. Regular always; the others on evidence."""
    needed = ["regular"]
    if re.search(r'font-weight["\s:=]*["\s]*(6\d\d|7\d\d|8\d\d|9\d\d|bold)', svg):
        needed.append("bold")
    if re.search(r'font-style["\s:=]*["\s]*italic', svg):
        needed.append("italic")
    return needed


def strip_existing(svg: str) -> str:
    return re.sub(re.escape(MARK_OPEN) + r".*?" + re.escape(MARK_CLOSE) + r"\s*",
                  "", svg, flags=re.S)


def normalise_size(svg: str) -> str:
    """Present at the canvas width, whatever the file was authored at.

    Four diagrams are EMITTED by figure scripts rather than hand-written, so a
    regeneration silently reverted them to width=1080 — and took their embedded
    font with it. Both properties are restored here, together, because they were
    lost together and a person will not remember to do two things.
    """
    m = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg)
    if not m:
        return svg
    vw, vh = float(m.group(1)), float(m.group(2))
    nh = round(1280 * vh / vw)
    svg = re.sub(r'\swidth="[\d.]+"', ' width="1280"', svg, count=1)
    svg = re.sub(r'\sheight="[\d.]+"', f' height="{nh:g}"', svg, count=1)
    return svg


def embed(path: Path) -> tuple[bool, int]:
    """Rewrite one file. Returns (changed, added bytes)."""
    original = path.read_text()
    svg = normalise_size(strip_existing(original))
    text = characters(svg)
    if not text:
        return False, 0

    blocks = []
    for face in faces_needed(svg):
        _src, wght, style = FACES[face]
        b64 = subset_b64(face, text)
        blocks.append(
            "    @font-face {\n"
            "      font-family: 'Source Sans 3';\n"
            f"      font-weight: {wght};\n"
            f"      font-style: {style};\n"
            f"      src: url(data:font/woff2;base64,{b64}) format('woff2');\n"
            "    }")

    style_block = (f"  {MARK_OPEN}\n"
                   "  <style>\n" + "\n".join(blocks) + "\n  </style>\n"
                   f"  {MARK_CLOSE}\n")

    # Straight after the opening <svg ...> tag, so it precedes anything that
    # uses it — including a <style> the diagram already had.
    m = re.match(r"\s*<svg\b[^>]*>\s*", svg, re.S)
    if not m:
        raise RuntimeError(f"{path.name}: no opening <svg> tag")
    out = svg[:m.end()] + style_block + svg[m.end():]
    if out == original:
        return False, 0
    path.write_text(out)
    return True, len(out) - len(original)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report unembedded files and exit non-zero")
    args = ap.parse_args()

    files = sorted(FIGURES.glob("d-*.svg"))
    if args.check:
        bad = [f.name for f in files
               if characters(f.read_text())
               and (MARK_OPEN not in f.read_text()
                    or ' width="1280"' not in f.read_text())]
        if bad:
            print(f"{len(bad)} diagram(s) carry no font, or are not presented "
                  f"at the canvas width:")
            for name in bad:
                print("  " + name)
            print("\nRun: python3 tools/embed_diagram_fonts.py")
            return 1
        print(f"{len(files)} diagrams: each carries the typeface it names")
        return 0

    total = 0
    for f in files:
        changed, delta = embed(f)
        total += max(delta, 0)
        if changed:
            print(f"  {f.name:26s} +{delta / 1024:6.1f} KB")
    print(f"\n{len(files)} diagrams, {total / 1024:,.0f} KB of font embedded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
